def info():
    print("O problema irá minimizar os custos da compra de bebidas para uma festa.")
    print("\nVariáveis: ")
    print("x[1] = Coca")
    print("x[3] = Guaraná")
    print("x[2] = Fanta")
    print("x[4] = Pepsi")
    print("x[5] = H2O")
    print("x[6] = Brahma")
    print("x[7] = Skol")
    print("x[8] = Heineken")
    print("x[9] = Suco")
    print("x[10] = Água")
    print("\nInstruções: ")
    print("1) O usuário monta sua planilha com os fornecedores disponiveis, bebidas (no máximo 10, sendo que os 5 primeiros devem ser os refrigerantes disponíveis, os próximos 3 as cervejas e os ultimos suco e água respectivamente) e seus valores;")
    print("2) Na execução ele deve escolher qual fornecedor irá contratar, qual tipo de festa vai ser (isso varia a quantidade de cada tipo de bebida) e o valor máximo que  ele pretende gastar;")
    print("3) Os valores serão equilibrados, para não ter muita de uma bebida e nenhuma da outra")
    print("Se o valor inserido para compra for válido, irá mostrar o resultado da otimização.")
    print("\nRestrições:")
    print("1) Tem que ter no mínimo um refrigerante, uma cerveja, água e suco")
    print("2) Só pode um tipo de cerveja")
    print("3) Só pode um tipo de refrigerante")
    print("4) O preço da compra deve ser menor ou igual ao valor total disponibilizado pelo usuário")
    print("5) Se for festa de criança o número de refrigerante deve ser maior que o de cerveja")
    print("6) Se for festa de adulto o número de cerveja deve ser maior que o de refrigerante")
    print("7) A soma da quantidade de água e suco deve ser no máximo a metade da soma de refrigerante e cerveja")
    # print("(8) Cada pessoa bebe aproximadamente 1L de cerveja e 500ML de refrigerante ou suco / água")
    print("\n")
