def info():
    print("O problema irá minimizar os custos da compra de bebidas para uma festa.")
    print("\nVariáveis: ")
    print("x[1] = Coca")
    print("x[3] = Guaraná")
    print("x[2] = Fanta")
    print("x[4] = Pepsi")
    print("x[5] = H2O")
    print("x[6] = Brahma")
    print("x[7] = Skol")
    print("x[8] = Heineken")
    print("x[9] = Suco")
    print("x[10] = Água")
    print("\nRestrições:")
    print("1) Tem que ter no mínimo um refrigerante, uma cerveja, água e suco")
    print("2) Só pode um tipo de cerveja")
    print("3) Só pode um tipo de refrigerante")
    print("4) O preço da compra deve ser menor ou igual ao valor total disponibilizado pelo usuário")
    print("5) Se for festa de criança o número de refrigerante deve ser maior que o de cerveja")
    print("6) Se for festa de adulto o número de cerveja deve ser maior que o de refrigerante")
    print("7) A soma da quantidade de água e suco deve ser no máximo a metade da soma de refrigerante e cerveja")
    # print("(8) Cada pessoa bebe aproximadamente 1L de cerveja e 500ML de refrigerante ou suco / água")
    print("\n")
