def info():
    print("O problema consiste em montar uma dieta diária focada apenas em proteína. O usuário digita a quantidade de calorias necessárias diariamente na sua dieta e o programa dirá qual a quantidade necessária de porções de 100g de cada alimento ele terá que comer.")
    print("\nVariáveis: ")
    print("x[1] = Arroz")
    print("x[3] = Feijão")
    print("x[2] = Açucar")
    print("x[4] = Alface")
    print("x[5] = Queijo")
    print("x[6] = Peixe")
    print("x[7] = Carne")
    print("x[8] = Tomate")
    print("x[9] = Suco de Laranja")
    print("x[10] = Leite")
    print("\nRestrições:")
    print("1) A quantidade de proteínas necessárias varia de acordo com a quantidade de nutrientes da dieta do usuário")
    print("2) Todos os 10 alimentos disponíveis no programa terão que estar presente, menos aqueles que se excluem")
    print("3) Só é permitido uma bebida na dieta")
    print("4) Só é permitido uma carne na dieta")
    print("5) É permitido no máximo 300g por alimento na dieta")
    print("6) O máximo de calorias deve ser 2000 Kcal")
